In [1]:
import numpy as np
import tensorflow as tf

print(tf.__version__)

/home/nil/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/nil/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/nil/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/nil/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarnin

1.14.0


In [2]:
const = tf.zeros((10))

In [3]:
fill_mat = tf.fill((4,4), 10)

In [4]:
my_zeros = tf.zeros((4,4))

In [6]:
myones = tf.ones((4,4))

In [7]:
myrandom = tf.random_normal((4,4), mean = 0, stddev = 1.0)

In [8]:
my_ops = [const, fill_mat, my_zeros, myones, myrandom]

In [9]:
sess = tf.InteractiveSession()

In [11]:
for op in my_ops:
    print(sess.run(op))
    print("\n")

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.09991977  1.3850472   1.5307139  -0.28894168]
 [ 1.4704344  -0.55562216 -0.00597079 -0.12104066]
 [ 0.8914399   1.531423   -0.57900935  0.72911006]
 [ 1.3908291   0.7985143   0.5352826  -0.17194134]]




In [13]:
a = tf.constant([[1,2], [3,4]])

In [14]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [15]:
b = tf.constant([[10], [100]])

In [16]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [17]:
result=tf.matmul(a,b)

In [18]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [19]:
result.eval()

array([[210],
       [430]], dtype=int32)

In [20]:
n1 = tf.constant(1)
n2 = tf.constant(2)
n3 = n1 + n2

In [21]:
with tf.Session() as sess:
    result = sess.run(n3)

In [22]:
print(result)

3


In [23]:
print(result)

3


In [24]:
graph_one = tf.get_default_graph()

In [25]:
print(graph_one)

In [26]:
graph_two = tf.Graph()

In [27]:
print(graph_two)